<?php $_code=$this->getMethodCode() ?>
<?php $cartDeal = PayRandom_PRPayment_Helper_Data::getCartDeal(); ?>
<?php if (!is_null($cartDeal->getFixedDiscount())): ?>

  <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
      <li>
          <label for="<?php echo $_code ?>_no_fixed_price" class="required"><em>*</em><?php echo $this->__('Ruleta');?></label>
          <span class="input-box">
            <input type="radio" id="<?php echo $_code ?>_no_fixed_price" name="payment[radio_fixed_price]" value="1" checked onclick="updatePrices();" />
          </span>
      </li>
      <li>
          <label for="<?php echo $_code ?>_fixed_price" class="required"><em>*</em><?php echo $this->__('Con precio fijo');?> <?php echo $this->helper('checkout')->formatPrice((1 - $cartDeal->getFixedDiscount()) * Mage::getSingleton('checkout/session')->getQuote()->getSubtotal()); ?> </label>
          <span class="input-box">
            <input type="radio" id="<?php echo $_code ?>_fixed_price" name="payment[radio_fixed_price]" value="2" onclick="updatePrices();" />
          </span>
      </li>
  </ul>
  <div>
      <?php echo $this->getMethod()->getConfigData('message');?>
  </div>
<?php else: ?>
  <?php Mage::GetSingleton("core/session")->setFixedPrice(0); ?>
<?php endif ?>

<script type="text/javascript">
var updatePrices = function () {
    if ($$('input:checked[name="payment[radio_fixed_price]"]')[0].value == "2") {
      $$(".prpayment-fixed-price").each(Element.show);
      $$(".prpayment-interval-price").each(Element.hide);
    }
    else {
      $$(".prpayment-fixed-price").each(Element.hide);
      $$(".prpayment-interval-price").each(Element.show);
    }
  };
</script>
