<?php
    $cartDeal = $this->getCartDeal(); 
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php else:?>
<?php
    $subTotal = Mage::getModel('checkout/cart')->getQuote()->getSubtotal();
    $difTotal = $this->getTotal()->getValue() - $subTotal;
    $shipping = $this->getTotal()->getAddress()->getShippingInclTax();
    $subTotal = $this->getTotal()->getValue() - $shipping;
?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
      <span class="prpayment-interval-price">
        <strong>
          <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $cartDeal->getMaximumDiscount()) * $subTotal + $shipping) . ' ' . $this->__('a') . ' ' . $this->helper('checkout')->formatPrice((1 - $cartDeal->getMinimumDiscount()) * $subTotal + $shipping) ?>
        </strong>
      </span>
      <span class="prpayment-fixed-price" style="display:none;">
        <strong>
          <?php echo $this->helper('checkout')->formatPrice((1 - $cartDeal->getFixedDiscount()) * $subTotal + $shipping); ?>
        </strong>
      </span>
    </td>
</tr>
<?php endif;?>
