<?php
    $cartDeal = $this->getCartDeal(); 
?>
<?php if ($this->displayBoth()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $cartDeal->getMaximumDiscount()) * $this->getTotal()->getValueExclTax()) ?>
        <?php echo $this->__('a'); ?>
        <?php echo $this->helper('checkout')->formatPrice((1 - $cartDeal->getMinimumDiscount()) * $this->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $cartDeal->getMaximumDiscount()) * $this->getTotal()->getValueInclTax()) ?>
        <?php echo $this->__('a'); ?>
        <?php echo $this->helper('checkout')->formatPrice((1 - $cartDeal->getMinimumDiscount()) * $this->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $cartDeal->getMaximumDiscount()) * $this->getTotal()->getValue()) ?>
        <?php echo $this->__('a'); ?>
        <?php echo $this->helper('checkout')->formatPrice((1 - $cartDeal->getMinimumDiscount()) * $this->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif;?>
