<?php if ($this->isPossibleOnepageCheckout()):?>
  <?php if (Mage::helper('core')->isModuleEnabled("Idev_OneStepCheckout")):?>
    <button type="button" title="<?php echo $this->__('Compra y Juega') ?>" onclick="window.location='<?php echo Mage::getUrl("onestepcheckout");?>'" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Compra y Juega') ?></span></span></button>
  <?php else:?>
    <button type="button" title="<?php echo $this->__('Compra y Juega') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Compra y Juega') ?></span></span></button>
  <?php endif?>
<?php endif?>
