<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
$minimumDiscount = false;
$maximumDiscount = false;
$fixedDiscount = false;

if(PayRandom_PRPayment_Helper_Data::checkCartCanApplyOffer()){
    $item = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
    $item = $item[0];
    $productId = $item->getProduct()->getId();//getProductId();
    $dealProduct = Mage::getModel('prpayment/dealproduct')->loadByProductId($productId);
    $deal = Mage::getModel('prpayment/deal')->load($dealProduct->getDealId());

    $minimumDiscount = $deal->getMinimumDiscount();
    $maximumDiscount = $deal->getMaximumDiscount();
    $fixedDiscount = $deal->getFixedDiscount();
}
?>

<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    <?php foreach($this->getItems() as $item): ?>
    <tr>
        <td class="name">
            <?php echo $item->getName(); ?>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="qty"><?php echo $item->getQty(); ?></td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
                <?php if($minimumDiscount || $maximumDiscount) { ?>
                  <span class="prpayment-interval-price">
                    <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $maximumDiscount) * $this->helper('checkout')->getSubtotalInclTax($item)) . ' ' . $this->__('a') . ' ' .
                    $this->helper('checkout')->formatPrice((1 - $minimumDiscount) * $this->helper('checkout')->getSubtotalInclTax($item)); ?>
                  </span>
                  <span class="prpayment-fixed-price" style="display:none;">
                    <?php
                        echo $this->helper('checkout')->formatPrice((1 - $fixedDiscount) * $this->helper('checkout')->getSubtotalInclTax($item));
                    ?>
                  </span>
                <?php } else { ?>
                    <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
                <?php } ?>
            <?php else: ?>
                    <?php if($minimumDiscount || $maximumDiscount) { ?>
                    <span class="prpayment-interval-price">
                      <?php echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $maximumDiscount) * $this->helper('checkout')->getRowTotal()) . ' ' . $this->__('a') . ' ' .
                      $this->helper('checkout')->formatPrice((1 - $minimumDiscount) * $this->helper('checkout')->getRowTotal()); ?>
                    </span>
                    <span class="prpayment-fixed-price" style="display:none;">
                      <?php echo $this->helper('checkout')->formatPrice((1 - $fixedDiscount) * $this->helper('checkout')->getRowTotal()); ?>
                  </span>
                    <?php }else{ ?>
                        <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
                    <?php } ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php 
    $ShippingValue = 0;
    $SubtotalValue = 0;
?>
<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();
        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php

            $code = $total->getCode();
            $value = $total->getValue();
            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
                $SubtotalValue = $value;
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                $ShippingValue = $value;
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
            }
            elseif($code == 'tax')    {
              $total_name = $total->getTitle();

              $total = $this->getQuote()->getGrandTotal();
              $shipping = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingInclTax();
              foreach ($fullInfo as $info) {
                $rates = current($info['rates']);
                $percent = $rates['percent'];
              }

              $_max_price_with_tax = ((1 - $minimumDiscount) * ($total - $shipping));
              $_max_price_without_tax = $_max_price_with_tax / (1 + ($percent / 100));
              $max_tax = $_max_price_with_tax - $_max_price_without_tax;

              $_min_price_with_tax = ((1 - $maximumDiscount) * ($total - $shipping));
              $_min_price_without_tax = $_min_price_with_tax / (1 + ($percent / 100));
              $min_tax = $_min_price_with_tax - $_min_price_without_tax;

              $_fixed_price_with_tax = ((1 - $fixedDiscount) * ($total - $shipping));
              $_fixed_price_without_tax = $_fixed_price_with_tax / (1 + ($percent / 100));
              $fixed_price = $_fixed_price_with_tax - $_fixed_price_without_tax;

            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php if(($minimumDiscount || $maximumDiscount) && ($code != 'shipping')) { ?>
            <?php if($code == 'grand_total'){ ?>
              <span class="prpayment-interval-price">
                <?php 
                    echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $maximumDiscount) * ($value - $ShippingValue)+ $ShippingValue) . ' ' . $this->__('a') . ' ' .
                    $this->helper('checkout')->formatPrice((1 - $minimumDiscount) * ($value - $ShippingValue) + $ShippingValue);
                ?>
              </span>
              <span class="prpayment-fixed-price" style="display:none;">
                <?php echo $this->helper('checkout')->formatPrice((1 - $fixedDiscount) * ($value - $ShippingValue) + $ShippingValue); ?>
              </span>
            <?php } elseif($code == 'tax'){ ?>
              <span class="prpayment-interval-price">
              <?php 
                echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice($min_tax) . ' ' .
                $this->__('a') . ' ' .
                $this->helper('checkout')->formatPrice($max_tax);
              ?>
              </span>
              <span class="prpayment-fixed-price" style="display:none;">
                <?php echo $this->helper('checkout')->formatPrice($fixed_price); ?>
              </span>
            <?php } else {?>
              <span class="prpayment-interval-price">
              <?php 
                  echo $this->__('de') . ' ' . $this->helper('checkout')->formatPrice((1 - $maximumDiscount) * $value) . ' ' . $this->__('a') . ' ' .
                  $this->helper('checkout')->formatPrice((1 - $minimumDiscount) * $value);
              ?>
              </span>
              <span class="prpayment-fixed-price" style="display:none;">
                <?php echo $this->helper('checkout')->formatPrice((1 - $fixedDiscount) * $value); ?>
              </span>
            <?php } ?>
            <?php }else{ ?>
                <?php echo $this->helper('checkout')->formatPrice($value); ?>
            <?php } ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
